package com.lms.model;

public enum NotificationType {
    LEAVE_REQUEST_SUBMITTED,
    LEAVE_REQUEST_APPROVED,
    LEAVE_REQUEST_REJECTED,
    LEAVE_REQUEST_CANCELLED,
    LEAVE_BALANCE_LOW,
    NEW_LEAVE_REQUEST_FOR_APPROVAL,
    SYSTEM_MESSAGE
}
